#!/bin/sh
#
# 把旧版 /etc/autoverify.conf 里的配置迁移到 UCI，然后归档旧文件。
# 由 /etc/uci-defaults 机制在首次安装后自动执行一次（执行完会自己删除）。

[ -f /etc/autoverify.conf ] || exit 0

USERNAME=""; PASSWORD=""; PORTAL_HOST=""; PORTAL_PORT=""; PORTAL_URL=""
PROBE_URLS=""; EXPECT_CODE=""; HTTP_TIMEOUT=""
CHECK_INTERVAL=""; RETRY_INTERVAL=""; MAX_RETRY_INTERVAL=""; VERBOSE=""
WAN_IF=""; HOTPLUG_IF=""
# shellcheck disable=SC1091
. /etc/autoverify.conf

[ -n "$USERNAME" ]     && uci set autoverify.main.username="$USERNAME"
[ -n "$PASSWORD" ]     && uci set autoverify.main.password="$PASSWORD"
[ -n "$PORTAL_HOST" ]  && uci set autoverify.portal.host="$PORTAL_HOST"
[ -n "$PORTAL_PORT" ]  && uci set autoverify.portal.port="$PORTAL_PORT"
[ -n "$PORTAL_URL" ]   && uci set autoverify.portal.url="$PORTAL_URL"
[ -n "$PROBE_URLS" ]   && uci set autoverify.tuning.probe_urls="$PROBE_URLS"
[ -n "$EXPECT_CODE" ]  && uci set autoverify.tuning.expect_code="$EXPECT_CODE"
[ -n "$HTTP_TIMEOUT" ] && uci set autoverify.tuning.http_timeout="$HTTP_TIMEOUT"
[ -n "$CHECK_INTERVAL" ]     && uci set autoverify.tuning.check_interval="$CHECK_INTERVAL"
[ -n "$RETRY_INTERVAL" ]     && uci set autoverify.tuning.retry_interval="$RETRY_INTERVAL"
[ -n "$MAX_RETRY_INTERVAL" ] && uci set autoverify.tuning.max_retry_interval="$MAX_RETRY_INTERVAL"
[ -n "$VERBOSE" ]            && uci set autoverify.tuning.verbose="$VERBOSE"
[ -n "$WAN_IF" ]       && uci set autoverify.network.wan_if="$WAN_IF"
[ -n "$HOTPLUG_IF" ]   && uci set autoverify.network.hotplug_if="$HOTPLUG_IF"
uci commit autoverify

mv /etc/autoverify.conf /etc/autoverify.conf.migrated
logger -t autoverify "已把旧版 /etc/autoverify.conf 迁移到 UCI (原文件改名为 .migrated)"
exit 0
